# Generated by Django 3.2.9 on 2021-11-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkesapp', '0002_auto_20211116_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='imagen',
            field=models.ImageField(upload_to='pkesapp\\images'),
        ),
    ]
