# Generated by Django 3.2.9 on 2021-11-18 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pkesapp', '0004_alter_galeria_imagen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Galeria',
            new_name='Servicios',
        ),
    ]
