# Generated by Django 3.2.9 on 2021-12-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkesapp', '0005_rename_galeria_servicios'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='name_item',
            field=models.CharField(default='hola', max_length=30),
            preserve_default=False,
        ),
    ]
