# Generated by Django 3.2.9 on 2021-12-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkesapp', '0007_remove_servicios_name_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
