# Generated by Django 3.2.9 on 2021-12-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkesapp', '0008_servicios_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicios',
            name='url',
        ),
        migrations.AddField(
            model_name='servicios',
            name='url_item',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
