# Generated by Django 3.2.9 on 2021-12-02 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pkesapp', '0009_auto_20211201_1553'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servicios',
            new_name='Services',
        ),
    ]
