# Generated by Django 3.2.9 on 2021-12-02 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pkesapp', '0010_rename_servicios_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='imagen',
            new_name='image',
        ),
    ]
