# Generated by Django 3.2.9 on 2021-12-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkesapp', '0011_auto_20211202_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(null=True, upload_to='gallery/sevices_app'),
        ),
    ]
